--  BiHA: состояние и конфигурация узлов кластера

\include ~/psqlrc/connect_biha_db.psql
\if :{?QUIT}
    \unset QUIT
    \quit
\endif

\include ~/psqlrc/biha_common.psql

select count(*) > 0 as table_callbacks_filled from biha.callbacks \gset

\if :biha_service_mode
    \echo :warn'WARNING: BiHA service mode ON (in all nodes)!':reset
\endif

\set title 'BiHA cluster state and config'
\include ~/psqlrc/title.psql

select 'now()' as function, now()::timestamptz(0)::text as return
union all
select 'biha.get_ssn()', biha.get_ssn()
union all
select E'biha.error_details()\n(curent node)', json_strip_nulls(to_json(e))::text from biha.error_details() as e where e.type != 'NO_ERROR';

SELECT
    concat(' ', s.id, E' \n\n') as "id ↓",

    s.term,

    \if `echo ':biha_config_columns' | grep -qx 'biha_listen_addresses' && echo 1 || echo 0`
        concat_ws(E'\n',
            c.biha_listen_addresses,
            nullif(c.name, c.biha_listen_addresses)
        ) as U&"host\000Aname",
    \else
        concat_ws(E'\n',
            n.host,
            nullif(c.name, n.host)
        ) as U&"host\000Aname",
    \endif

    concat_ws(E'\n',
        concat_ws(' ',
            e1.state_symbol,
            s.state,
            case c.mode when 'referee'          then '(no WAL)'
                        when 'referee_with_wal' then '(with WAL)'
            end
        ),
        nullif(s.last_known_state, s.state)
    ) as U&"biha_state\000Alast_known",

    concat_ws(E'\n',
        concat_ws(' ',
            e2.pg_state_symbol || ' ' || m.pg_state,
            m.startup_progress || '%' -- показывает прогресс запуска в процентах, когда значение pg_state — Startup.
        ),
        e3.state_symbol || ' ' || n.state
    ) as U&"pg_state\000Aconn_state",

    concat_ws(E'\n',
        pro.interval_pretty(s.since_last_hb),
        s.online
    ) AS U&"last_hb\000Aonline",

    concat_ws(E'\n',
        c.heartbeat_send_period::text || ' ms',
        c.heartbeat_max_lost
    ) as U&"hb_send_period\000Ahb_max_lost",

    concat_ws(E'\n',
        c.repl_pref_roles,
        lpad(case when c.max_replicas = 2147483647 then '∞' else c.max_replicas::text end, 12, ' ')
    ) as U&"pref_roles\000Amax_replicas",

    c.priority::text || ' ms' as U&"priority\000A(delay)",

    c.nquorum as U&"nquorum\000A(on fail)", -- минимальное число узлов, которые должны проголосовать за нового лидера при отказе текущего лидера

    c.minnodes as U&"minnodes\000A(for L rw)", -- минимальное число работающих узлов, при котором лидер будет открыт для пишущих транзакций

    -- значение поля MIN параметра synchronous_standby_names,
    -- т.е. минимальное число синхронных резервных узлов, которые должны быть доступны, чтобы лидер продолжал подтверждать транзакции
    c.sync_standbys_min as U&"sync_standbys_min\000A(for L commit)",

    concat_ws(E'\n',
        c.can_be_leader,
        c.can_vote
    ) as U&"can_be_leader\000Acan_vote",

    -- Postgres Pro (enterprise) 18.4.1 2a1f89e2632  ERROR:  column "deny_wal_sources" does not exist
    \if `echo ':biha_config_columns' | grep -qx 'deny_wal_sources' && echo 1 || echo 0`
        concat_ws(E'\n',
            c.no_wal_on_follower::text || ' ms',
            c.deny_wal_sources
        ) as U&"no_wal_on_follower\000Adeny_wal_sources"
    \else
        c.no_wal_on_follower::text || ' ms' as U&"no_wal_on_follower\000A(timeout)"
    \endif

FROM biha.status_v     AS s
JOIN biha.nodes_v      AS n ON n.id = s.id
JOIN biha.config()     AS c ON c.id = s.id
JOIN biha.monitoring() AS m ON m.id = s.id
--LEFT JOIN pg_stat_replication AS r ON r.application_name = CONCAT('biha_node_', s.id)
CROSS JOIN coalesce(
    case when s.state = 'LEADER_RO'  then :'symbol_hollow_red'
         when s.state in ('LEADER_RW', 'FOLLOWER', 'FRONT_FOLLOWER') then :'symbol_green'
         when s.state = 'REFEREE'    then :'symbol_blue'
         when s.state = 'NODE_ERROR' then :'symbol_red'
         when s.state = 'UNKNOWN'    then :'symbol_white'
         else /* PRESTARTUP, STARTUP, CSTATE_FORMING, FOLLOWER_OFFERED, CANDIDATE */ :'symbol_yellow' -- переходные статусы
    end
) e1(state_symbol)
CROSS JOIN coalesce(
    case when m.pg_state in ('Recovery', 'Promoted') then :'symbol_green' -- штатное состояние для реплики / мастера
         when s.state = 'REFEREE' and m.pg_state = 'Recovery pause'  then :'symbol_blue' -- штатное состояние для рефери
         else /* Prestartup, Startup, Promoting */ :'symbol_yellow' -- переходные статусы
    end
) e2(pg_state_symbol)
CROSS JOIN coalesce(
    case when n.state in ('ACTIVE', 'IDLE') then :'symbol_green'
         else /* INIT, CONNECTING, SSLCONNECT, SSLACCEPT */ :'symbol_yellow' -- переходные статусы
    end
) e3(state_symbol)
ORDER BY s.id;

-- показываем таблицу biha.callbacks только если она не пустая
\if :table_callbacks_filled

    \set title 'BiHA callbacks'
    \include ~/psqlrc/title.psql

    table biha.callbacks;
\endif


\unset title
\include ~/psqlrc/title.psql

\include ~/psqlrc/connect_restore.psql