\echo :hint'Install...':reset

\if :pg_is_in_recovery
    \echo :error'ERROR: connect to server role "primary" required':reset
    \quit
\endif

\if :is_superuser
\else
    \echo :error'ERROR: connect a user (for example, postgres) with the superuser attribute required':reset
    \quit
\endif

\include ~/psqlrc/quiet_in.psql
    select exists (select from pg_catalog.pg_database where datname = 'psqlrc_db') as psqlrc_db_exists \gset
    select exists (select from pg_catalog.pg_database where datname = 'biha_db') as biha_db_exists \gset
\include ~/psqlrc/quiet_out.psql

\if :psqlrc_db_exists
    \echo :warn'database "psqlrc_db" already exists':reset
    \quit
\endif

\set DBNAME_ORIGINAL :DBNAME

/*
В одну и туже базу невозможно установить одно и то же расширение в разные схемы, будет ошибка.
Другие расширения (например, "pgpro_pwr") тоже могут установить зависимое расширение "dblink" в базу "postgres".
Чтобы не было конфликтов при установке расширения "dblink", используем отдельную базу "psqlrc_db".
*/
CREATE DATABASE psqlrc_db;
\connect psqlrc_db
\echo
\echo :head'Database "':DBNAME'"':reset
START TRANSACTION;
    \include ~/psqlrc/install.psql
COMMIT;

\if :biha_db_exists
    \connect biha_db
    \echo
    \echo :head'Database "':DBNAME'"':reset
    START TRANSACTION;
        \include ~/psqlrc/install.psql
    COMMIT;
\endif

\connect :DBNAME_ORIGINAL

\echo :hint'For user "psqlrc_user", do it on all servers of database cluster:':reset
\echo :hint'1. Save password in file "~/.pgpass"':reset
\echo :hint'2. Check (if necessary) remote authentification possibility (see file "':hba_file'")':reset

\if :ERROR
    \echo :error'Install fail':reset
\else
    \echo :succ'Install success':reset
\endif
