\echo :hint'Reinstall...':reset

\if :pg_is_in_recovery
    \echo :error'ERROR: connect to server role "primary" required':reset
    \quit
\endif

\if :is_superuser
\else
    \echo :error'ERROR: connect a user (for example, postgres) with the superuser attribute required':reset
    \quit
\endif

\include ~/psqlrc/quiet_in.psql
    select exists (select from pg_catalog.pg_database where datname = 'biha_db') as biha_db_exists \gset
\include ~/psqlrc/quiet_out.psql

\set DBNAME_ORIGINAL :DBNAME

\if :biha_db_exists
    \if `test ':DBNAME' != 'biha_db' && echo 1 || echo 0`
        \connect biha_db
    \endif

    \echo
    \echo :head'Database "':DBNAME'"':reset
    START TRANSACTION;
        DROP SCHEMA IF EXISTS pro CASCADE;
        \include ~/psqlrc/install.psql
    COMMIT;
\endif

\if `test ':DBNAME' != 'postgres' && echo 1 || echo 0`
    \connect postgres
\endif

\echo
\echo :head'Database "':DBNAME'"':reset
START TRANSACTION;
    DROP SCHEMA IF EXISTS pro CASCADE;
    \include ~/psqlrc/install.psql
COMMIT;

\if `test ':DBNAME' != ':DBNAME_ORIGINAL' && echo 1 || echo 0`
    \connect :DBNAME_ORIGINAL
\endif

\if :ERROR
    \echo :error'Reinstall fail':reset
\else
    \echo :succ'Reinstall success':reset
\endif
