\echo :hint'Reinstall...':reset

\if :pg_is_in_recovery
    \echo :error'ERROR: connect to server role "primary" required':reset
    \quit
\endif

\if :is_superuser
\else
    \echo :error'ERROR: connect a user (for example, postgres) with the superuser attribute required':reset
    \quit
\endif

\include ~/psqlrc/quiet_in.psql
    select exists (select from pg_database where datname = 'biha_db') as biha_db_exists \gset
\include ~/psqlrc/quiet_out.psql

\set DBNAME_ORIGINAL :DBNAME

-- old version of psqlrc
\connect postgres
\echo
\echo :head'Database "':DBNAME'"':reset
DROP SCHEMA IF EXISTS pro CASCADE;

DROP DATABASE IF EXISTS psqlrc_db WITH (FORCE);
CREATE DATABASE psqlrc_db;
\connect psqlrc_db
\echo
\echo :head'Database "':DBNAME'"':reset
START TRANSACTION;
    \include ~/psqlrc/install.psql
COMMIT;

\if :biha_db_exists
    \connect biha_db
    \echo
    \echo :head'Database "':DBNAME'"':reset
    START TRANSACTION;
        DROP SCHEMA IF EXISTS pro CASCADE;
        \include ~/psqlrc/install.psql
    COMMIT;
\endif

\connect :DBNAME_ORIGINAL

\if :ERROR
    \echo :error'Reinstall fail':reset
\else
    \echo :succ'Reinstall success':reset
\endif
