\echo :hint'Reinstall...':reset

\if :pg_is_in_recovery
    \echo :error'ERROR: connect to server role "primary" required':reset
    \quit
\endif

\if :is_superuser
\else
    \echo :error'ERROR: connect a user (for example, postgres) with the superuser attribute required':reset
    \quit
\endif

\include ~/psqlrc/quiet_in.psql
    select exists (select from pg_catalog.pg_database where datname = 'psqlrc_db') as psqlrc_db_exists \gset
    select exists (select from pg_catalog.pg_database where datname = 'biha_db') as biha_db_exists \gset
\include ~/psqlrc/quiet_out.psql

\if :psqlrc_db_exists
\else
    \echo :warn'database "psqlrc_db" does not exist':reset
    \echo :hint'HINT: type ":INSTALL"':reset
    \quit
\endif

\set DBNAME_ORIGINAL :DBNAME

\connect postgres
\echo
\echo :head'Database "':DBNAME'"':reset
DROP SCHEMA IF EXISTS pro CASCADE; -- old version of psqlrc

\connect psqlrc_db
\echo
\echo :head'Database "':DBNAME'"':reset
START TRANSACTION;
    DROP SCHEMA IF EXISTS pro CASCADE;
    \include ~/psqlrc/install.psql
COMMIT;

\if :biha_db_exists
    \connect biha_db
    \echo
    \echo :head'Database "':DBNAME'"':reset
    START TRANSACTION;
        DROP SCHEMA IF EXISTS pro CASCADE;
        \include ~/psqlrc/install.psql
    COMMIT;
\endif

\connect :DBNAME_ORIGINAL

\if :ERROR
    \echo :error'Reinstall fail':reset
\else
    \echo :succ'Reinstall success':reset
\endif
