--  BiHA: топология, состояние и конфигурация узлов кластера (в одной компактной таблице)

\include ~/psqlrc/connect_biha_db.psql
\if :{?QUIT}
    \unset QUIT
    \quit
\endif

\include ~/psqlrc/biha_common.psql

\if :biha_service_mode
    \echo :warn'WARNING: BiHA service mode ON (in all nodes)!':reset
\endif

\set title 'BiHA cluster tolopogy, state and config'
\include ~/psqlrc/title.psql

select
    \if `echo ':biha_config_columns' | grep -qx 'deny_wal_sources' && echo 1 || echo 0`
        concat_ws('     ',
            case when not coalesce(t.is_primary, false) then coalesce(pn.id::text, :'symbol_red') end,
            c.deny_wal_sources
        ) as U&"parent_id\000Adeny_wal_sources",
    \else
        case when not t.is_primary then coalesce(pn.id::text, :'symbol_red') end as parent_id,
    \endif

    n.id as "id ↓",

    state_symbol || ' ' || s.state as state,

    sync_state as mode,

    concat_ws(' ',
        ping_latency_pretty,
        repeat(' ', length('time_diff') - length(ping_latency_pretty || ping_time_diff_pretty) - 1) || ping_time_diff_pretty
    ) as U&"ping\000Atime_diff",

    concat_ws('    ',
        lpad(c.priority::text, 3, ' ') || ' ms',
        case when c.max_replicas = 2147483647 then '∞' else c.max_replicas::text end
    ) as U&"priority\000Amax_replicas",

    concat_ws('    ',
        rpad(c.repl_pref_roles, 2, ' '),
        c.nquorum,
        c.minnodes
    ) as U&"pref_roles\000Anquorum minnodes",

    concat_ws('    ',
        c.can_be_leader,
        c.can_vote
    ) as U&"can_be_leader\000Acan_vote",

    case when is_primary then regexp_replace(guc_primary->>'synchronous_standby_names', '\m[a-z_]+_(?=\d)', 'id=', 'g')
         else concat(
                           pro.size_pretty(last_lsn  - sent_lsn),   -- data sending WAL stream to replica via network by walsender
                  ' + ' || pro.size_pretty(sent_lsn  - write_lsn),  -- data receiving WAL stream on replica from network by walreciever
                  ' + ' || pro.size_pretty(write_lsn - flush_lsn),  -- data writing WAL on disk on replica by walreciever
                  ' + ' || pro.size_pretty(flush_lsn - replay_lsn), -- data applying (replaying) WAL as a recovery process
                  ' = ' || case when (last_lsn - replay_lsn) > 1024*1024*100 then :'symbol_warning' || ' ' else '' end
                        || pro.size_pretty(last_lsn  - replay_lsn)  -- total
              )
    end as U&"lag_size\000Asend+write+flush+replay=total"

from biha.status_v     as s
join biha.nodes_v      as n on n.id = s.id
join biha.config()     as c on c.id = s.id
join biha.monitoring() as m on m.id = s.id
left join pro.cluster_topology() as t  on  n.host IN (t.host,        host(t.addr))
left join biha.nodes_v           as pn on pn.host IN (t.parent_host, host(t.parent_host))
left join coalesce(
    case when t.ping_latency <  '50ms'::interval then :'symbol_green'
         when t.ping_latency < '100ms'::interval then :'symbol_yellow'
         else :'symbol_red'
    end
    || ' ' || pro.interval_pretty(t.ping_latency)
) as ping_latency_pretty on true
left join greatest(t.ping_time_diff, t.ping_time_diff * -1) as p(abs_ping_time_diff) on true
left join coalesce(
    case when abs_ping_time_diff <  '50ms'::interval then :'symbol_green'
         when abs_ping_time_diff < '100ms'::interval then :'symbol_yellow'
         else :'symbol_red'
    end
    || ' ' || pro.interval_pretty(p.abs_ping_time_diff)
) as ping_time_diff_pretty on true
cross join coalesce(
   case when s.state = 'LEADER_RO'  then :'symbol_hollow_red'
        when s.state in ('LEADER_RW', 'FOLLOWER', 'FRONT_FOLLOWER') then :'symbol_green'
        when s.state = 'REFEREE'    then :'symbol_blue'
        when s.state = 'NODE_ERROR' then :'symbol_red'
        when s.state = 'UNKNOWN'    then :'symbol_white'
        else /* PRESTARTUP, STARTUP, CSTATE_FORMING, FOLLOWER_OFFERED, CANDIDATE */ :'symbol_yellow'
   end
) as state_symbol
order by n.id;

\unset title
\include ~/psqlrc/title.psql

\include ~/psqlrc/connect_restore.psql
