\echo :hint'Uninstall...':reset

\if :pg_is_in_recovery
    \echo :error'ERROR: connect to server role "primary" required':reset
    \quit
\endif

\if :is_superuser
\else
    \echo :error'ERROR: connect a user (for example, postgres) with the superuser attribute required':reset
    \quit
\endif

\include ~/psqlrc/quiet_in.psql
    select exists (select from pg_catalog.pg_database where datname = 'biha_db') as biha_db_exists \gset
\include ~/psqlrc/quiet_out.psql

\set DBNAME_ORIGINAL :DBNAME

\connect postgres
\echo
\echo :head'Database "':DBNAME'"':reset
DROP SCHEMA IF EXISTS pro CASCADE; -- old version of psqlrc

\echo
\echo :head'Database "psqlrc_db"':reset
DROP DATABASE IF EXISTS psqlrc_db WITH (FORCE);

\if :biha_db_exists
    \connect biha_db
    \echo
    \echo :head'Database "':DBNAME'"':reset
    DROP SCHEMA IF EXISTS pro CASCADE;
\endif

\echo
\echo :head'Global objects':reset
START TRANSACTION;
    DROP ROLE IF EXISTS psqlrc_role;
    DROP USER IF EXISTS psqlrc_user;
COMMIT;

\if `test ':DBNAME' != ':DBNAME_ORIGINAL' && echo 1 || echo 0`
    \connect :DBNAME_ORIGINAL
\endif

\if :ERROR
    \echo :error'Uninstall fail':reset
\else
    \echo :succ'Uninstall success':reset
\endif
