-- агрегированная информация из `pg_stat_activity`

\set title 'Stat activity groups counts'
\include ~/psqlrc/title.psql

select
    backend_type    as "backend_type ↓",
    datname         as "database ↓",
    state           as "state ↓",
    usename         as "user ↓",
    wait_event_type as "wait_event_type ↓",
    wait_event      as "wait_event ↓",
    count(*)        as "count_total ↓",
    concat_ws(' ',
        lpad((count(*) filter (where state_change < now() - interval '1 second'))::text, 3, ' '),
        lpad((count(*) filter (where state_change < now() - interval '5 second'))::text, 3, ' '),
        lpad((count(*) filter (where state_change < now() - interval '1 minute'))::text, 3, ' '),
        lpad((count(*) filter (where state_change < now() - interval '1 hour'))::text,   3, ' ')
    ) as U&"count_state_changed\000A> 1s/5s/1m/1h ago"
from pg_stat_activity
group by backend_type, datname, state, usename, wait_event_type, wait_event
order by backend_type, datname, state, usename, wait_event_type, wait_event
\g | sed 's/↵/ /g'

\unset title
\include ~/psqlrc/title.psql
