-- именованные SQL запросы для быстрого доступа

select

    -- Топология кластера СУБД. Возвращает серверы: мастер и зависимые реплики, включая каскадные.
    case when exists(select from pg_catalog.pg_namespace where nspname = 'pro') then
        $sql$
        $sql$
        else $sql$
                \echo :hint'first, run `psql -v pro=install -c '''' ':DBNAME'` and `nano ~/.pgpass` to save/check password exists for user postgres':reset
             $sql$
        end as "T",

    --  BiHA: состояние и конфигурация узлов кластера
    case when exists(select from pg_catalog.pg_namespace where nspname = 'pro') then
        $sql$
        $sql$
        else $sql$
                \echo :hint'first, run `psql -v pro=install -c '''' biha_db` and `nano ~/.pgpass` to save/check password exists for user postgres':reset
             $sql$
        end as "B",

    -- BiHA шпаргалка: сопоставление параметров конфигурации с функциями управления
    $sql$
    $sql$ as "BB"

\gset
