\echo :hint'Uninstall...':reset

\if :pg_is_in_recovery
    \echo :error'ERROR: connect to server role "primary" required':reset
    \quit
\endif

\if :is_superuser
\else
    \echo :error'ERROR: connect a user (for example, postgres) with the superuser attribute required':reset
    \quit
\endif

START TRANSACTION;
    DROP SCHEMA IF EXISTS pro CASCADE;
    DROP USER IF EXISTS psqlrc_user;
COMMIT;

\if :ERROR
    \echo :error'Uninstall fail':reset
\else
    \echo :succ'Uninstall success':reset
\endif
