\echo :hint'Reinstall...':reset

\if :pg_is_in_recovery
    \echo :error'ERROR: connect to server role "primary" required':reset
    \quit
\endif

\if :is_superuser
\else
    \echo :error'ERROR: connect a user (for example, postgres) with the superuser attribute required':reset
    \quit
\endif

START TRANSACTION;
    DROP SCHEMA IF EXISTS pro CASCADE;
    -- DROP USER IF EXISTS psqlrc_user; -- NOT DROP!

    \include ~/psqlrc/install.psql
COMMIT;

\if :ERROR
    \echo :error'Reinstall fail':reset
\else
    \echo :succ'Reinstall success':reset
\endif
