-- именованные SQL запросы для быстрого доступа
select
    -- who am i (информация о текущем пользователе, схеме и т.д.)
    -- https://postgrespro.ru/docs/postgresql/current/functions-info
    $sql$
        SELECT now()::timestamptz(0) as "now()",
               pg_backend_pid()      as "pg_backend_pid()",
               coalesce((SELECT usesuper FROM pg_user WHERE usename = CURRENT_USER), false) as is_superuser,
               CURRENT_USER          as "CURRENT_USER",
               SESSION_USER          as "SESSION_USER",
               current_database()    as "current_database()",
               current_schema()      as "current_schema()",
               current_schemas(true) as "current_schemas(true)",
               pg_current_xact_id_if_assigned()                 as "current_xact_id",     -- идентификатор текущей транзакции или NULL, если она ещё не имеет идентификатора
               pg_xact_status(pg_current_xact_id_if_assigned()) as "current_xact_status", -- состояние фиксации транзакции: in progress / committed / aborted
               pg_current_logfile()  as "pg_current_logfile()",
               inet_client_addr()    as "inet_client_addr()",
               inet_client_port()    as "inet_client_port()",
               inet_server_addr()    as "inet_server_addr()",
               inet_server_port()    as "inet_server_port()",
               pg_jit_available()    as "pg_jit_available()",
               pg_numa_available()   as "pg_numa_available()",
               version()             as "version()",
               unicode_version()     as "unicode_version()",
               icu_unicode_version() as "icu_unicode_version()"
        \gx
    $sql$ as "W",

    -- агрегированная информация из `pg_stat_activity`
    $sql$
        select
            backend_type,
            datname,
            state,
            usename,
            wait_event_type,
            wait_event,
            count(*) as "count_total",
            concat_ws(' ',
                lpad((count(*) filter (where state_change < now() - interval '1 second'))::text, 3, ' '),
                lpad((count(*) filter (where state_change < now() - interval '5 second'))::text, 3, ' '),
                lpad((count(*) filter (where state_change < now() - interval '1 minute'))::text, 3, ' '),
                lpad((count(*) filter (where state_change < now() - interval '1 hour'))::text,   3, ' ')
            ) as U&"count_state_changed\000A> 1s/5s/1m/1h ago"
        from pg_stat_activity
        group by backend_type, datname, state, usename, wait_event_type, wait_event
        order by backend_type, datname, state, usename, wait_event_type, wait_event;
    $sql$ as "A",

    -- Топология кластера СУБД. Возвращает серверы: мастер и зависимые реплики, включая каскадные.
    case when exists(select from pg_catalog.pg_namespace where nspname = 'pro') then
        /*
        Значений полей для вывода много. Необходимо, чтобы таблица уместилось на широкоформатный экран разрешением 2880×1800 (16:10).
        Для этого применены следующие хитрости:
        1) Названия колонок и значения выводятся в две строки вместо одной
        2) Несколько логически взаимосвязанных значений объединены в одной колонке
        3) В дате-времени удалены миллисекунды
        4) Для размеров в байтах и интервалов времени выводится только значимая информация
        */
        $sql$
            -- к сожалению, внутри литерала команда \pset не работает и возвращает ошибку
            -- select now()::timestamptz(0) as now \gset
            -- \pset title 'Cluster topology (at ':now')'

            select
                concat('   ', level, E'\n\n') as "level ↓",
                case when is_primary then 'primary' else 'replica' end as role,

                concat_ws(E'\n',
                    nullif((regexp_match(guc_replica->>'primary_conninfo', '\mhost=(\S+)'))[1], parent_addr::text),
                    parent_addr
                ) as U&"parent_host\000Aparent_addr",

                concat_ws(E'\n',
                    coalesce(
                        client_hostname, -- это поле будет не null только в случае соединений по IP и только при включённом режиме log_hostname
                        guc_biha->>'host'
                    ),
                    addr
                ) as U&"host\000Aaddr",

                concat_ws(E'\n',
                    pro.interval_pretty(ping_latency),
                    lpad(pro.interval_pretty(greatest(ping_time_diff, ping_time_diff * -1)), 9, ' ')
                ) as U&"ping\000Atime_diff",

                concat_ws(E'\n',
                    sync_state, -- async/potential/sync/quorum
                    sync_priority
                ) as U&"mode ↑\000Apriority",

                concat_ws(E'\n',
                    state,      -- startup / catchup / streaming / backup / stopping
                    pause_state -- not paused / pause requested / paused
                ) as "state ↓",

                concat(
                             pro.size_pretty(last_lsn  - sent_lsn),   -- data sending WAL stream to replica via network by walsender
                    ' + ' || pro.size_pretty(sent_lsn  - write_lsn),  -- data receiving WAL stream on replica from network by walreciever
                    ' + ' || pro.size_pretty(write_lsn - flush_lsn),  -- data writing WAL on disk on replica by walreciever
                    ' + ' || pro.size_pretty(flush_lsn - replay_lsn), -- data applying (replaying) WAL as a recovery process
                    ' = ' || pro.size_pretty(last_lsn  - replay_lsn)
                ) as U&"lag_size\000Asend+write+flush+replay=total",

                concat_ws(' < ',
                    pro.interval_pretty(write_lag), -- time elapsed between flushing recent WAL locally and receiving notification that this standby server has written it (but not yet flushed it or applied it)
                    pro.interval_pretty(flush_lag), -- time elapsed between flushing recent WAL locally and receiving notification that this standby server has written and flushed it (but not yet applied it)
                    pro.interval_pretty(replay_lag) -- time elapsed between flushing recent WAL locally and receiving notification that this standby server has written, flushed and applied it
                ) as U&"lag_time\000Awrite<flush<replay",

                concat_ws(E'\n',
                    pro.interval_pretty(reply_ago),
                    case when not is_primary then (guc_replica->>'hot_standby_feedback')::bool end
                ) as U&"reply_ago\000Afeedback",

                concat_ws(E'\n',
                    lpad(pro.interval_pretty(start_uptime), 12, ' '),
                    lpad(pro.interval_pretty(load_uptime),  12, ' ')
                ) as U&"start_uptime\000Aload_uptime",

                concat_ws(E'\n',
                    pro.size_pretty(last_lsn - restart_lsn),
                    pro.size_pretty(safe_wal_size)
                ) as U&"hold_wal_size\000Asafe_wal_size",

                concat_ws(E'\n',
                    slot_name,
                    concat(wal_status, ', reason:' || invalidation_reason, ', since:' || inactive_since::timestamptz(0)::text)
                ) as U&"slot_name\000Awal_status",

                concat_ws(E'\n',
                    concat(
                        slot_type, -- physical/logical
                        case when slot_type = 'logical' then concat(', db:', database, ', failover:', failover, ', synced:', synced) end
                    ),
                    concat(active, ' ', temporary)
                ) as U&"slot_type\000Aactive temp"

            from pro.pg_cluster_topology as t
            order by t.level, t.sync_state desc, t.state;

            --\pset title
        $sql$
        else $sql$
                \echo :hint'first, run `psql -v pro=install -c '''' ':DBNAME'` and `nano ~/.pgpass` to save/check password exists for user postgres':reset
             $sql$
        end as "T",

    --  BiHA: состояние и конфигурация узлов кластера
    case when exists(select from pg_catalog.pg_namespace where nspname = 'pro') then
        $sql$
            select 'now()' as function, now()::timestamptz(0)::text as return
            union all
            select 'biha.get_ssn()', biha.get_ssn()
            union all
            select 'biha.error_details()', json_strip_nulls(to_json(e))::text from biha.error_details() as e where e.type != 'NO_ERROR';

            SELECT
                concat(' ', s.id, E' \n\n') as "id ↓",

                s.term,

                concat_ws(E'\n',
                    n.host, nullif(c.name, n.host)
                ) as U&"host\000Aname",

                concat_ws(E'\n',
                    s.state,
                    nullif(s.last_known_state, s.state)
                ) as U&"biha_state\000Alast_known",

                concat_ws(E'\n',
                    concat_ws(' ',
                        m.pg_state, -- текущее состояние СУБД, возможные значения: Prestartup, Startup, Recovery, Recovery_Pause, Promoting, Promoted
                        m.startup_progress || '%' -- показывает прогресс запуска в процентах, когда значение pg_state — Startup.
                    ),
                    n.state -- состояние соединения узла: ACTIVE/CONNECTING/IDLE/INIT/SSLCONNECT/SSLACCEPT
                ) as U&"pg_state\000Aconn_state",

                concat_ws(E'\n',
                    c.mode, -- текущий режим работы узла: regular, referee, referee_with_wal.
                    c.service_mode
                ) as U&"referee_mode\000Aservice_mode",

                concat_ws(E'\n',
                    pro.interval_pretty(s.since_last_hb),
                    s.online
                ) AS U&"last_hb\000Aonline",

                concat_ws(E'\n',
                    c.heartbeat_send_period::text || ' ms',
                    c.heartbeat_max_lost
                ) as U&"hb_send_period\000Ahb_max_lost",

                concat_ws(E'\n',
                    c.repl_pref_roles,
                    lpad((nullif(c.max_replicas, 2147483647))::text, 12, ' ')
                ) as U&"pref_roles\000Amax_replicas",

                c.priority::text || ' ms' as U&"priority\000A(delay)",

                c.nquorum as U&"nquorum\000A(on fail)", -- минимальное число узлов, которые должны проголосовать за нового лидера при отказе текущего лидера

                c.minnodes as U&"minnodes\000A(for L rw)", -- минимальное число работающих узлов, при котором лидер будет открыт для пишущих транзакций

                -- значение поля MIN параметра synchronous_standby_names,
                -- т.е. минимальное число синхронных резервных узлов, которые должны быть доступны, чтобы лидер продолжал подтверждать транзакции
                nullif(c.sync_standbys_min, -1) as U&"sync_standbys_min\000A(for L commit)",

                concat_ws(E'\n',
                    c.can_be_leader,
                    c.can_vote
                ) as U&"can_be_leader\000Acan_vote",

                -- deny_wal_sources,  -- Postgres Pro (enterprise) 18.4.1 2a1f89e2632  ERROR:  column "deny_wal_sources" does not exist

                c.no_wal_on_follower::text || ' ms' as U&"no_wal_on_follower\000A(timeout)"

            FROM biha.status_v     AS s
            JOIN biha.nodes_v      AS n ON n.id = s.id
            JOIN biha.config()     AS c ON c.id = s.id
            JOIN biha.monitoring() AS m ON m.id = s.id
            --LEFT JOIN pg_stat_replication AS r ON r.application_name = CONCAT('biha_node_', s.id)
            ORDER BY s.id;

            -- select count(*) > 0 as callbacks_exists from biha.callbacks \gset --TODO показывать таблицу только если она не пустая
            -- select * from biha.callbacks;

        $sql$
        else $sql$
                \echo :hint'first, run `psql -v pro=install -c '''' biha_db` and `nano ~/.pgpass` to save/check password exists for user postgres':reset
             $sql$
        end as "B",

    -- BiHA шпаргалка: сопоставление параметров конфигурации с функциями управления
    $sql$
        with s (name, value) as (
            select s.name, s.setting
            from pg_settings as s
            where s.name ~ '^biha\.[a-z]' or s.name = 'synchronous_standby_names'
        ),
        -- получаем параметры конфигурации (для текущего узла), которые невозможно изменить с помощью ALTER SYSTEM SET или просмотреть через SHOW / current_setting()
        c (name, value) as (
            select '*.' || case when j.key = 'repl_pref_roles' then 'preferred_roles' else j.key end,
                   j.value
            from biha.config() as c
            cross join json_each_text(row_to_json(c)) as j
            where c.id = current_setting('biha.id')::int
        ),
        f (name, funcs) as (
            values
            ('synchronous_standby_names',  'biha.get_ssn() text;
                                            biha.set_sync_standbys(ANY int) bool;
                                            biha.set_sync_standbys_min(MIN int) bool;
                                            biha.set_ssn(VARIADIC ids int) bool;
                                            biha.add_to_ssn(id int) returns bool;
                                            biha.remove_from_ssn(id int) bool'),
            ('biha.proxima_status',        'biha.enable_proxima() bool; biha.disable_proxima() bool'),
            ('biha.heartbeat_max_lost',    'biha.set_heartbeat_max_lost(int) bool'),
            ('biha.heartbeat_send_period', 'biha.set_heartbeat_send_period(int) bool'),
            ('biha.no_wal_on_follower',    'biha.set_no_wal_on_follower(int) bool'),
            ('biha.minnodes',              'biha.set_minnodes(id int, minnodes int) bool'),
            ('biha.nquorum',               'biha.set_nquorum(id int, nquorum int) bool'),
            ('biha.can_be_leader',         'biha.set_can_be_leader(id int, can_be_leader bool) bool'),
            ('biha.can_vote',              'biha.set_can_vote(id int, can_vote bool) bool'),
            ('biha.deny_wal_sources',      'biha.set_deny_wal_sources(id int, deny_node_id int[]) bool'),
            ('biha.max_replicas',          'biha.set_max_replicas(id int, value int) bool'),
            ('biha.preferred_roles',       'biha.set_pref_roles(id int, value text) bool'),
            ('biha.priority',              'biha.set_priority(id int, value int) bool')
        ),
        h (name, funcs) as (
            values
            -- эти параметры конфигурации хранятся в файле pg_biha/biha.conf, и их невозможно изменить с помощью ALTER SYSTEM SET или просмотреть через SHOW
            ('*',                 'biha.add_node(id int, parent_id int) bool;
                                   biha.remove_node(id int) bool;
                                   biha.set_leader(id int) bool'),
            ('*.can_vote',        'biha.set_can_vote(id int, can_vote bool) bool'),
            ('*.minnodes',        'biha.set_minnodes(id int, minnodes int) bool'),
            ('*.max_replicas',    'biha.set_max_replicas(id int, value int) bool'),
            ('*.nquorum',         'biha.set_nquorum(id int, nquorum int) bool'),
            ('*.preferred_roles', 'biha.set_pref_roles(id int, value text) bool'),
            ('*.priority',        'biha.set_priority(id int, value int) bool')
        ),
        t (name, value, funcs) as (
            select s.name, s.value, f.funcs
            from s
            left join f on f.name = s.name
            UNION ALL
            select h.name,
                   case when h.name = '*' then './pg_biha/biha.conf' else c.value end,
                   h.funcs
            from h
            left join c on h.name = c.name
        )
        select
            row_number() over (order by t.name) as "#",
            t.name as "setting_name ↓",
            nullif(trim(t.value), '') as setting_value,
            regexp_replace(t.funcs, ';\s*', E'\n', 'g') as management_functions
        from t
        order by t.name;
    $sql$ as "BB"

\gset
