-- Топология кластера СУБД. Возвращает серверы: мастер и зависимые реплики, включая каскадные.

\include ~/psqlrc/quiet_in.psql
    select exists (select from pg_catalog.pg_namespace where nspname = 'pro') as schema_pro_exists \gset
\include ~/psqlrc/quiet_out.psql

\if :schema_pro_exists
\else
    \echo :hint'type ":INSTALL" and check (if necessary) remote authentification possibility for user postgres in every server of cluster (see files "~/.pgpass" and "':hba_file'")':reset
    \quit
\endif


\set title 'Cluster topology'
\include ~/psqlrc/title.psql

/*
Значений полей для вывода много. Необходимо, чтобы таблица уместилось на широкоформатный экран разрешением 2880×1800 (16:10).
Для этого применены следующие хитрости:
1) Названия колонок и значения выводятся в две строки вместо одной
2) Несколько логически взаимосвязанных значений объединены в одной колонке
3) Для размеров в байтах и интервалов времени выводится только значимая информация
*/
select
    concat('   ', level, E'\n\n') as "level ↓",

    concat_ws(E'\n',
        case when is_primary then 'primary' else 'replica' end,
        trim((regexp_match(pg_version, ' \d+(?:\.\d+)+'))[1]) -- X.Y[.Z]
    ) as U&"role\000Aversion",

    concat_ws(E'\n',
        nullif(parent_host, host(parent_addr)),
        host(parent_addr)
    ) as U&"parent_host\000Aparent_addr",

    concat_ws(E'\n',
        nullif(host, host(addr)),
        host(addr)
    ) as U&"host\000Aaddr",

    concat_ws(E'\n',
        case when ping_latency       > '1s'::interval then '⚠️' else '' end || pro.interval_pretty(ping_latency),
        case when abs_ping_time_diff > '1s'::interval then '⚠️' else '' end || lpad(pro.interval_pretty(abs_ping_time_diff), 9, ' ')
    ) as U&"ping\000Atime_diff",

    concat_ws(E'\n',
        sync_state, -- async/potential/sync/quorum
        sync_priority
    ) as U&"mode ↑\000Apriority",

    concat_ws(E'\n',
        state,      -- startup / catchup / streaming / backup / stopping
        pause_state -- not paused / pause requested / paused
    ) as "state ↓",

    case when is_primary
         -- слишком длинное значение synchronous_standby_names разбиваем на несколько срок
         then trim(regexp_replace('SSN: ' || (guc_primary->>'synchronous_standby_names'), '(.{22}[a-z_\-\d)]+)', E'\\1\n', 'g'), E' \n')
         else concat(
                           pro.size_pretty(last_lsn  - sent_lsn),   -- data sending WAL stream to replica via network by walsender
                  ' + ' || pro.size_pretty(sent_lsn  - write_lsn),  -- data receiving WAL stream on replica from network by walreciever
                  ' + ' || pro.size_pretty(write_lsn - flush_lsn),  -- data writing WAL on disk on replica by walreciever
                  ' + ' || pro.size_pretty(flush_lsn - replay_lsn), -- data applying (replaying) WAL as a recovery process
                  ' = ' || pro.size_pretty(last_lsn  - replay_lsn)  -- total
              )
    end as U&"lag_size\000Asend+write+flush+replay=total",

    concat_ws(' < ',
        pro.interval_pretty(write_lag), -- time elapsed between flushing recent WAL locally and receiving notification that this standby server has written it (but not yet flushed it or applied it)
        pro.interval_pretty(flush_lag), -- time elapsed between flushing recent WAL locally and receiving notification that this standby server has written and flushed it (but not yet applied it)
        pro.interval_pretty(replay_lag) -- time elapsed between flushing recent WAL locally and receiving notification that this standby server has written, flushed and applied it
    ) as U&"lag_time\000Awrite<flush<replay",

    concat_ws(E'\n',
        pro.interval_pretty(reply_ago),
        case when not is_primary then (guc_replica->>'hot_standby_feedback')::bool end
    ) as U&"reply_ago\000Afeedback",

    concat_ws(E'\n',
        lpad(pro.interval_pretty(start_uptime), 12, ' '),
        lpad(pro.interval_pretty(load_uptime),  12, ' ')
    ) as U&"start_uptime\000Aload_uptime",

    concat_ws(E'\n',
        pro.size_pretty(last_lsn - restart_lsn),
        pro.size_pretty(safe_wal_size)
    ) as U&"hold_wal_size\000Asafe_wal_size",

    concat_ws(E'\n',
        slot_name,
        concat(wal_status, ', reason:' || invalidation_reason, ', since:' || inactive_since::timestamptz(0)::text)
    ) as U&"slot_name\000Awal_status",

    concat_ws(E'\n',
        concat(
            slot_type, -- physical/logical
            case when slot_type = 'logical' then concat(', db:', database, ', failover:', failover, ', synced:', synced) end
        ),
        concat(active, ' ', temporary)
    ) as U&"slot_type\000Aactive temp"

from pro.pg_cluster_topology as t
cross join greatest(t.ping_time_diff, t.ping_time_diff * -1) as p(abs_ping_time_diff)
order by t.level, t.sync_state desc, t.state;

\unset title
\include ~/psqlrc/title.psql
