\echo :hint'Install...':reset

\if :pg_is_in_recovery
    \echo :error'ERROR: connect to server role "primary" required':reset
    \quit
\endif

\if :is_superuser
\else
    \echo :error'ERROR: connect a user (for example, postgres) with the superuser attribute required':reset
    \quit
\endif

\include ~/psqlrc/quiet_in.psql
    select exists (select from pg_catalog.pg_namespace where nspname = 'pro') as schema_pro_exists \gset
\include ~/psqlrc/quiet_out.psql

\if :schema_pro_exists
    \echo :warn'schema "pro" already exists':reset
    \quit
\endif

\include ~/psqlrc/quiet_in.psql
    select exists (select from pg_catalog.pg_database where datname = 'biha_db') as biha_db_exists \gset
\include ~/psqlrc/quiet_out.psql

\set DBNAME_ORIGINAL :DBNAME

\if :biha_db_exists
    \if `test ':DBNAME' != 'biha_db' && echo 1 || echo 0`
        \connect biha_db
    \endif

    \echo
    \echo :head'Database "':DBNAME'"':reset
    START TRANSACTION;
        \include ~/psqlrc/install.psql
    COMMIT;
\endif

\if `test ':DBNAME' != 'postgres' && echo 1 || echo 0`
    \connect postgres
\endif

\echo
\echo :head'Database "':DBNAME'"':reset
START TRANSACTION;
    \include ~/psqlrc/install.psql
COMMIT;

\if `test ':DBNAME' != ':DBNAME_ORIGINAL' && echo 1 || echo 0`
    \connect :DBNAME_ORIGINAL
\endif

\echo :hint'For user "psqlrc_user", do it on all servers of database cluster:':reset
\echo :hint'1. Save password in file "~/.pgpass"':reset
\echo :hint'2. Check (if necessary) remote authentification possibility (see file "':hba_file'")':reset

\if :ERROR
    \echo :error'Install fail':reset
\else
    \echo :succ'Install success':reset
\endif
