\echo :hint'Install...':reset

\if :pg_is_in_recovery
    \echo :error'ERROR: connect to server role "primary" required':reset
    \quit
\endif

\if :is_superuser
\else
    \echo :error'ERROR: connect a user (for example, postgres) with the superuser attribute required':reset
    \quit
\endif

START TRANSACTION;
    \include ~/psqlrc/install.psql
COMMIT;

\if :ERROR
    \echo :error'Install fail':reset
\else
    \echo :succ'Install success':reset
\endif
