--  BiHA: состояние и конфигурация узлов кластера

\set title 'BiHA cluster state and config'
\include ~/psqlrc/title.psql

\if :schema_pro_exists
\else
    \echo :hint'type ":INSTALL" and run "\\! nano ~/.pgpass" to save/check password exists for user postgres':reset
    \quit
\endif

\if `test ':DBNAME' != 'biha_db' && echo 1 || echo 0`
    \echo :error'please, connect to database "biha_db"':reset
    \echo :hint'HINT: type "\\c biha_db"':reset
    \quit
\endif


select 'now()' as function, now()::timestamptz(0)::text as return
union all
select 'biha.get_ssn()', biha.get_ssn()
union all
select 'biha.error_details()', json_strip_nulls(to_json(e))::text from biha.error_details() as e where e.type != 'NO_ERROR';

SELECT
    concat(' ', s.id, E' \n\n') as "id ↓",

    s.term,

    concat_ws(E'\n',
        n.host, nullif(c.name, n.host)
    ) as U&"host\000Aname",

    concat_ws(E'\n',
        s.state,
        nullif(s.last_known_state, s.state)
    ) as U&"biha_state\000Alast_known",

    concat_ws(E'\n',
        concat_ws(' ',
            m.pg_state, -- текущее состояние СУБД, возможные значения: Prestartup, Startup, Recovery, Recovery_Pause, Promoting, Promoted
            m.startup_progress || '%' -- показывает прогресс запуска в процентах, когда значение pg_state — Startup.
        ),
        n.state -- состояние соединения узла: ACTIVE/CONNECTING/IDLE/INIT/SSLCONNECT/SSLACCEPT
    ) as U&"pg_state\000Aconn_state",

    concat_ws(E'\n',
        c.mode, -- текущий режим работы узла: regular, referee, referee_with_wal.
        c.service_mode
    ) as U&"referee_mode\000Aservice_mode",

    concat_ws(E'\n',
        pro.interval_pretty(s.since_last_hb),
        s.online
    ) AS U&"last_hb\000Aonline",

    concat_ws(E'\n',
        c.heartbeat_send_period::text || ' ms',
        c.heartbeat_max_lost
    ) as U&"hb_send_period\000Ahb_max_lost",

    concat_ws(E'\n',
        c.repl_pref_roles,
        lpad((nullif(c.max_replicas, 2147483647))::text, 12, ' ')
    ) as U&"pref_roles\000Amax_replicas",

    c.priority::text || ' ms' as U&"priority\000A(delay)",

    c.nquorum as U&"nquorum\000A(on fail)", -- минимальное число узлов, которые должны проголосовать за нового лидера при отказе текущего лидера

    c.minnodes as U&"minnodes\000A(for L rw)", -- минимальное число работающих узлов, при котором лидер будет открыт для пишущих транзакций

    -- значение поля MIN параметра synchronous_standby_names,
    -- т.е. минимальное число синхронных резервных узлов, которые должны быть доступны, чтобы лидер продолжал подтверждать транзакции
    c.sync_standbys_min as U&"sync_standbys_min\000A(for L commit)",

    concat_ws(E'\n',
        c.can_be_leader,
        c.can_vote
    ) as U&"can_be_leader\000Acan_vote",

    -- deny_wal_sources,  -- Postgres Pro (enterprise) 18.4.1 2a1f89e2632  ERROR:  column "deny_wal_sources" does not exist

    c.no_wal_on_follower::text || ' ms' as U&"no_wal_on_follower\000A(timeout)"

FROM biha.status_v     AS s
JOIN biha.nodes_v      AS n ON n.id = s.id
JOIN biha.config()     AS c ON c.id = s.id
JOIN biha.monitoring() AS m ON m.id = s.id
--LEFT JOIN pg_stat_replication AS r ON r.application_name = CONCAT('biha_node_', s.id)
ORDER BY s.id;


-- показываем таблицу biha.callbacks только если она не пустая
\set QUIET 1
\timing 0
select count(*) > 0 as callbacks_exists from biha.callbacks \gset
\if :QUIET_ORIGINAL
    \timing 0
\else
    \timing 1
\endif
\set QUIET :QUIET_ORIGINAL

\if :callbacks_exists

    \set title 'BiHA callbacks'
    \include ~/psqlrc/title.psql

    select * from biha.callbacks;
\endif


\unset title
\include ~/psqlrc/title.psql
