\include ~/psqlrc/quiet_in.psql
    select exists (select from pg_database where datname = 'psqlrc_db') as psqlrc_db_exists \gset
\include ~/psqlrc/quiet_out.psql

\if :psqlrc_db_exists
\else
    \echo :error'database "psqlrc_db" does not exist':reset
    \echo :hint'HINT: type ":INSTALL"':reset
    -- при использовании \quit в скрипте прекращается только выполнение этого скрипта, поэтому делаем выход ещё из родительского скрипта
    \set QUIT 1
    \quit
\endif

\set DBNAME_ORIGINAL :DBNAME
\if `test ':DBNAME' != 'psqlrc_db' && echo 1 || echo 0`
    \include ~/psqlrc/quiet_in.psql
        \connect psqlrc_db
    \include ~/psqlrc/quiet_out.psql
\endif
