-- Global objects

SELECT EXISTS (SELECT FROM pg_roles WHERE rolname = 'psqlrc_user') AS psqlrc_user_exists \gset

\if :psqlrc_user_exists
    \echo 'User "psqlrc_user" already exists, skipping'
\else
    \echo 'Create user "psqlrc_user"'
    CREATE USER psqlrc_user;
\endif

------------------------------------------------------------------------------------------------------------------------
-- Current database objects

CREATE SCHEMA pro AUTHORIZATION postgres;

CREATE EXTENSION dblink SCHEMA pro;
--ALTER EXTENSION dblink OWNER TO psqlrc_user; -- command is not support

\include ~/psqlrc/install/ping.sql
ALTER FUNCTION pro.ping(connection_str text) OWNER TO postgres;

\include ~/psqlrc/install/interval_pretty.sql
ALTER FUNCTION pro.interval_pretty(interval) OWNER TO postgres;

\include ~/psqlrc/install/size_pretty.sql
ALTER FUNCTION pro.size_pretty(bigint) OWNER TO postgres;
ALTER FUNCTION pro.size_pretty(numeric) OWNER TO postgres;

\include ~/psqlrc/install/dblink_u.sql
ALTER FUNCTION pro.dblink_u(connection_str text, sql text, record_definition text) OWNER TO postgres;

\include ~/psqlrc/install/cluster_topology.sql
ALTER VIEW pro.cluster_topology OWNER TO postgres;

------------------------------------------------------------------------------------------------------------------------
-- Grant permissions to database objects
GRANT pg_monitor TO psqlrc_user; -- for extension pg_buffercache
GRANT USAGE ON SCHEMA pro TO psqlrc_user;
GRANT SELECT ON pro.cluster_topology TO psqlrc_user;

--GRANT SELECT ON pro.cluster_topology TO psqlrc_user;

\if :psqlrc_user_exists
\else
    \echo :hint'Please, for database user "psqlrc_user" set password and save it in file "~/.pgpass" on all servers of database cluster.':reset
    /*
    Указывая команде "ALTER USER user_name WITH PASSWORD 'new_password'" незашифрованный пароль, следует проявлять осторожность.
    Пароль будет передаваться на сервер открытым текстом и может также записаться в историю команд клиента или в протокол работы сервера.
    В psql есть команда \password, с помощью которой можно сменить пароль в хешированном виде, не рискуя его рассекретить.
    */
    \password psqlrc_user
\endif
