-- выполнять под суперпользователем postgres  TODO - добавить здесь проверку

-- Objects global

/*
DO $$
BEGIN
    CREATE USER psqlrc_user WITH PASSWORD 'E74rPpWtbnVR2WvZgfMF7TduA'; -- IF NOT EXISTS does not support!
    GRANT pg_monitor TO psqlrc_user; -- for extension pg_buffercache
EXCEPTION
    WHEN duplicate_object THEN RAISE NOTICE 'User "psqlrc_user" already exists, skipping';
END
$$;
*/

------------------------------------------------------------------------------------------------------------------------
-- Objects in current database

CREATE SCHEMA pro /*AUTHORIZATION psqlrc_user*/;

CREATE EXTENSION dblink SCHEMA pro;
--ALTER EXTENSION dblink OWNER TO psqlrc_user; -- not supported

\include ~/psqlrc/install/os_home_dir.sql
--alter function pro.os_home_dir(user_name text) owner to postgres;

\include ~/psqlrc/install/read_pgpass.sql
--alter function pro.read_pgpass(filename text) owner to postgres;

\include ~/psqlrc/install/ping.sql
--ALTER FUNCTION pro.ping(connection_str text) OWNER TO psqlrc_user;

\include ~/psqlrc/install/interval_pretty.sql
--ALTER FUNCTION pro.interval_pretty(interval) OWNER TO psqlrc_user;

\include ~/psqlrc/install/size_pretty.sql
--ALTER FUNCTION pro.size_pretty(bigint) OWNER TO psqlrc_user;
--ALTER FUNCTION pro.size_pretty(numeric) OWNER TO psqlrc_user;

\include ~/psqlrc/install/cluster_topology.sql
--ALTER VIEW pro.cluster_topology OWNER TO psqlrc_user;

--GRANT SELECT ON pro.cluster_topology TO psqlrc_user;