/*
Последняя версия:  https://github.com/rin-nas/psqlrc
Документация psql: https://postgrespro.ru/docs/postgresql/current/app-psql
*/

-- важно не сломать текущее поведение psql, на которое в скриптах уже заложились!
\if :{?pro}
    -- psql запущен с флагом -v pro=
\else
    \quit
\endif

------------------------------------------------------------------------------------------------------------------------
-- стили и ограничения

-- цвета
\set red       '\033[38;5;196m'
\set green     '\033[38;5;10m'
\set blue      '\033[38;5;12m'
\set lightblue '\033[38;5;81m'
\set yellow    '\033[38;5;220m'
\set orange    '\033[38;5;208m'
\set cyan      '\033[38;5;6m'
\set magenta   '\033[38;5;13m'
\set gray      '\033[38;5;7m'
\set white     '\033[38;5;15m'

-- стили
\set bold      '\033[1m'
\set italic    '\033[3m'
\set underline '\033[4m'
\set crossed   '\033[9m'
\set blink     '\033[5m'
\set reset     '\033[0m'

-- типы сообщений
\set error :red
\set warn  :orange
\set hint  :yellow
\set succ  :green
\set head  :bold

-- стили для некоторых слов
\set primary_style          '\033[48;5;88m'
\set replica_active_style   '\033[48;5;130m'
\set replica_inactive_style '\033[48;5;8m'

-- ограничение длительности выполнения "тяжёлых" команд типа `du -sh`
\set os_command_timeout '20s'

------------------------------------------------------------------------------------------------------------------------
-- настройки psql общие

-- запоминаем флаг отображения информационных сообщений
\set QUIET_ORIGINAL :QUIET

-- скрываем информационные сообщения для команд \pset и \timing
-- установка значения 1 эквивалента параметру командной строки `psql -q`
\set QUIET 1

-- прекращаем обработку команд после возникновения ошибки, в интерактивном режиме psql вернётся в командную строку
\set ON_ERROR_STOP 1

-- откатываем ошибки только в интерактивных сеансах, но не в скриптах
\set ON_ERROR_ROLLBACK interactive

-- для каждой базы данных ведём отдельный файл истории выполненных команд
\set HISTFILE ~/.psql_history.:DBNAME

-- устанавливаем максимальное число команд, которые будут сохраняться в истории команд (по умолчанию 500)
\set HISTSIZE 9000

-- не добавляем в историю строки, которые в ней уже есть
\set HISTCONTROL ignoredups

-- отображаем в таблицах рамки с непрерывными линиями
\pset linestyle unicode

-- отображаем значения NULL
\pset null '¤'
--\pset null '∅' -- не везде корректно отображается из-за отсутствия правильного шрифта

-- рамки вокруг таблицы со всех сторон
\pset border 2

-- отображаем количество срок под таблицами
\pset footer on

------------------------------------------------------------------------------------------------------------------------
-- настройки psql для редактора и пейджера

-- редактор для команды \e
\setenv PSQL_EDITOR 'nano'

-- пейджер (если результат запроса не помещается на экране, он пропускается через эту программу)
\set pspg_installed `command -v pspg > /dev/null 2>&1 && echo 1 || echo 0`
\set less_installed `command -v less > /dev/null 2>&1 && echo 1 || echo 0`
\if :pspg_installed
    \pset expanded off
    \setenv PSQL_PAGER       'pspg --freezecols=4 --reprint-on-exit --blackwhite --on-sigint-exit --no-sound'
    \setenv PSQL_WATCH_PAGER 'pspg --freezecols=4 --reprint-on-exit --blackwhite --on-sigint-exit --no-sound --stream'
\elif :less_installed
    \setenv PSQL_PAGER 'less -iMFXSx4R'
\endif

------------------------------------------------------------------------------------------------------------------------
-- получаем значения параметров СУБД для PROMPT1
select
    pg_is_in_recovery(),
    coalesce((SELECT rolsuper FROM pg_roles WHERE rolname = CURRENT_ROLE), false) as is_superuser,

    trim((regexp_match(coalesce(
        -- example: Postgres Pro (shardman) 18.3.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 13.3.1 20250418 (RED SOFT 13.3.1-3), 64-bit
        (select nullif(trim(setting), '') from pg_settings where name = 'pgpro_version' limit 1),

        -- example: PostgreSQL 18.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 13.3.1 20250418 (RED SOFT 13.3.1-3), 64-bit
        -- example: PostgreSQL 16.11 (Ubuntu 16.11-1.pgdg24.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0, 64-bit
        -- example: PostgreSQL 19beta2 (Debian 19~beta2-1...) on x86_64-pc-linux-gnu...
        version()
    ), '^.+? \d+(?:\.\d+)*\S* '))[1]) as pg_version,

    coalesce(
        (select ' ' || nullif(trim(setting), '') from pg_settings where name = 'pgpro_build' limit 1), -- example: c3d046b75bf
        ''
    ) as pg_build
\gset

------------------------------------------------------------------------------------------------------------------------
-- настраиваем приглашения командной строки PROMPT1 и PROMPT2

\set PROMPT2 '%R%x%# '

-- YYYY-MM-DD HH:MM:SS+HH:MM  user@host[IP]:/current_path/
\set PROMPT_OS '%`date --rfc-3339=seconds | sed ''s/:00$//''`  %`whoami`@%`hostname`[%`hostname -I | xargs`] %`pwd`'

-- pg_version pg_build  user@host:port/database
\set PROMPT_PG :pg_version'':pg_build'  %n@%M:%>/%/'

\if `test ':pro' = color && echo 1 || echo 0`
    -- в Ubuntu 26.04 LTS в терминале v3.58.0 для GNOME 49 цветная строка отображается, но слишком длинная обрезается!
    \set PROMPT_PG :pg_version'':gray'':pg_build' ':yellow'%n':cyan'@':orange'%M':cyan':':green'%>':blue'/%/':reset
\endif

\set PROMPT1 '\n':PROMPT_OS'\n':PROMPT_PG'\n':PROMPT2

------------------------------------------------------------------------------------------------------------------------

-- короткие команды для DBA
\include ~/psqlrc/commands.psql

------------------------------------------------------------------------------------------------------------------------
\if :QUIET_ORIGINAL
    -- psql запущен с флагом -q

    -- скрываем длительность выполнения запроса
    \timing 0

    -- скрываем количество строк под таблицей
    \pset footer off
\else

    \echo '~/.psqlrc version: '`cat $(find ~/psqlrc/ -type f | sort) | cksum | grep -oP '^\S+' | xargs printf '%x'`'  https://github.com/rin-nas/psqlrc'

    \include ~/psqlrc/info.psql

    \if :pg_buffercache_installed
        SELECT
            pg_size_pretty(COUNT(*) * 8192) AS total_shared_buffers,
            pg_size_pretty(COUNT(*) FILTER (WHERE usagecount IS NOT NULL) * 8192) AS used_shared_buffers,
            ROUND(100.0 * COUNT(*) FILTER (WHERE usagecount IS NOT NULL) / COUNT(*)) AS used_shared_buffers_percent
        FROM pg_buffercache
        \gset
    \endif

    \if :is_local_connection

        \set postgres_pid         `ps -p :pg_backend_pid -o ppid= | xargs`
        \set systemd_unit_name    `ps -p :pg_backend_pid -o unit= | xargs`
        \set systemd_unit_enabled `systemctl is-enabled :systemd_unit_name`
        \set bin_directory        `dirname $(realpath /proc/:pg_backend_pid/exe)`

        \if :{?data_directory}
        \else
            -- если прав доступа не хватило, то пробуем получить data_directory альтернативным способом
            \set data_directory `ps -p :postgres_pid -o cmd= | grep -oP -- ' -D \K\S+'`
        \endif

        -- определяем роль СУБД - мастер или реплика
        \if `test -r ':data_directory' && test -x ':data_directory' && echo 1 || echo 0`
            -- если прав доступа хватило
            \set is_primary `test -f ':data_directory/standby.signal' && echo 0 || echo 1`
        \endif

    \endif

    \if :{?is_primary}
    \else
        -- если прав доступа не хватило, получаем is_primary альтернативным способом
        -- но определять роль СУБД через SQL функцию pg_is_in_recovery() не всегда корректно
        \set is_primary `test ':pg_is_in_recovery' = f && echo 1 || echo 0`
    \endif

    \set wal_directory :data_directory'/pg_wal'

    \if :{?logging_collector}
        \if :logging_collector
            \if :{?log_directory}
                \if `echo :log_directory | grep -qP '^/' && echo 1 || echo 0`
                \else
                    \set log_directory :data_directory'/':log_directory
                \endif
            \else
                \set log_directory :data_directory
            \endif
        \else
            \unset log_directory
        \endif
    \endif

    -- вычисляем ссылки и размеры директорий
    \if `test ':pro' = 1 && echo 1 || echo 0`
        \if :is_local_connection
            select now() as calc_dir_size_start \gset

            -- data_directory
            \set data_directory_used_size `timeout ':os_command_timeout' du -sh ':data_directory' | grep -oP '^\S+'`
            \set df `df -h ':data_directory' | tail -1`
            select a[4]           as data_directory_free_size,
                   left(a[5], -1) as data_directory_used_percent,
                   a[6]           as data_directory_mounted_to
            from regexp_split_to_array(:'df', '\s+') as a
            where trim(:'df') != ''
            \gset

            -- wal_directory
            \set wal_real_directory `readlink -f ':wal_directory'`
            \if `test ':wal_directory' = ':wal_real_directory' && echo 1 || echo 0`
                \unset wal_real_directory
                \set wal_dir :wal_directory
            \else
                \set wal_dir :wal_real_directory
            \endif
            \set wal_directory_used_size `timeout ':os_command_timeout' du -sh ':wal_dir' | grep -oP '^\S+'`
            \set df `df -h ':wal_dir' | tail -1`
            select a[4]           as wal_directory_free_size,
                   left(a[5], -1) as wal_directory_used_percent,
                   a[6]           as wal_directory_mounted_to
            from regexp_split_to_array(:'df', '\s+') as a
            where trim(:'df') != ''
            \gset

            -- log_directory
            \if :{?log_directory}
                \set log_files_used_size `timeout ':os_command_timeout' find ':log_directory' -maxdepth 1 -type f -exec du -ch {} + | tail -1 | grep -oP '^\S+'`
                \set df `df -h ':log_directory' | tail -1`
                select a[4]           as log_directory_free_size,
                       left(a[5], -1) as log_directory_used_percent,
                       a[6]           as log_directory_mounted_to
                from regexp_split_to_array(:'df', '\s+') as a
                where trim(:'df') != ''
                \gset
            \endif

            select now() - :'calc_dir_size_start' > '1s'::interval as is_calc_dir_size_slow \gset
        \endif
    \endif

    --------------------------------------------------------------------------------------------------------------------
    -- выводим информационные сообщения

    \if `test ':pro' = 1 && echo 1 || echo 0`
        \if :is_local_connection
            \echo :head'\n# OS ':reset
            \echo `top -bn2 | head -5`
        \endif
    \endif

    \echo :head'\n# SERVER':reset

    \if :{?systemd_unit_name}
        \echo 'Systemd unit:          ':systemd_unit_name' (pid: ':postgres_pid', autostart: ':systemd_unit_enabled')'
    \endif

    \echo 'Started at:            ':started_at' (':start_uptime' ago)'
    \echo 'Config loaded at:      ':loaded_at' (':load_uptime' ago)'

    \if :{?bin_directory}
        \echo 'Bin directory:         ':bin_directory
    \endif

    \if :{?data_directory}
        \set str 'Data directory:        ':data_directory
        \if :{?data_directory_used_size}
            \set color :reset
            \if `test ':data_directory_used_percent' -gt 95 && echo 1 || echo 0`
                \set color :red
            \elif `test ':data_directory_used_percent' -gt 90 && echo 1 || echo 0`
                \set color :orange
            \endif
            \set str :str:color' (size: ':data_directory_used_size' used, ':data_directory_free_size' free)':reset
        \endif
        \echo :str
    \endif

    \if :{?wal_directory}
        \set str 'WAL directory:         ':wal_directory
        \if :{?wal_real_directory}
            \set str :str' → ':wal_real_directory
        \endif
        \if :{?wal_directory_used_size}
            \set color :reset
            \if `test ':wal_directory_used_percent' -gt 95 && echo 1 || echo 0`
                \set color :red
            \elif `test ':wal_directory_used_percent' -gt 90 && echo 1 || echo 0`
                \set color :orange
            \endif
            \set str :str:color' (size: ':wal_directory_used_size' used, ':wal_directory_free_size' free)':reset
        \endif
        \echo :str
    \endif

    \if :{?log_directory}
        \set str 'Log directory:         ':log_directory
        \if :{?log_files_used_size}
            \set color :reset
            \if `test ':log_directory_used_percent' -gt 90 && echo 1 || echo 0`
                \set color :red
            \elif `test ':log_directory_used_percent' -gt 80 && echo 1 || echo 0`
                \set color :orange
            \endif
            \set str :str:color' (size: ':log_files_used_size' files used, ':log_directory_free_size' free)':reset
        \endif
        \echo :str
    \endif

    \if :{?used_connections_percent}
        \set color :reset
        \if `test ':used_connections_percent' -gt 85 && echo 1 || echo 0`
            \set color :red
        \elif `test ':used_connections_percent' -gt 70 && echo 1 || echo 0`
            \set color :orange
        \endif
        \echo 'Connections:           ':used_connections' of ':max_connections' ':color'(used ':used_connections_percent'%)':reset
    \endif

    \if :{?used_shared_buffers}
        \echo 'Shared buffers/cache:  ':used_shared_buffers' of ':total_shared_buffers' (used ':used_shared_buffers_percent'%)'
    \elif :{?shared_buffers}
        \echo 'Shared buffers/cache:  ':shared_buffers
    \endif

    \if :is_primary
        \echo 'Server role:           ':primary_style'primary':reset' (read-write)'
    \else
       \if :wal_receive_count
           \echo 'Server role:           ':replica_active_style'replica':reset' (read only)'
           \echo 'WAL receive (1):       ':wal_receive_from
       \else
           \echo 'Server role:           ':replica_inactive_style'replica':reset' (read only)'
           \echo 'WAL receive (0):       ':warn'connection to primary is not established or lost':reset
       \endif
    \endif

    \echo 'WAL send (':wal_send_count'):          ':wal_send_to

    \echo 'Synchronous commit:    ':synchronous_commit
    \echo 'Sync. standby names:   ':synchronous_standby_names

    \if :{?shared_preload_libraries}
        \echo 'Shared preload libs:   ':shared_preload_libraries
    \endif

    \if :{?walsender_plugin_libraries}
        \echo 'Walsender plugin libs: ':walsender_plugin_libraries
    \endif

    \if :is_archive_active
        \echo 'Archive mode:          ':archive_mode' (timeout: ':archive_timeout')'
        \if :{?archive_command}
            \echo 'Archive command:       ':archive_command
        \endif
        \if :{?restore_command}
            \echo 'Restore command:       ':restore_command
        \endif
    \else
        \echo 'Archive mode:          ':archive_mode
    \endif

    --------------------------------------------------------------------------------------------------------------------
    \echo :head'\n# DATABASE':reset

    \echo 'Current database:      ':db_name' (size: ':db_size' total)'
    \echo 'Cache hit ratio:       ':db_cache_hit_ratio'%'

    \if :{?installed_extensions}
        \echo 'Installed extensions:  ':installed_extensions
    \endif

    --------------------------------------------------------------------------------------------------------------------
    \echo :head'\n# SHORT COMMANDS':reset

    \echo ':H — Help and full list of short commands'
    \echo

    --------------------------------------------------------------------------------------------------------------------
    -- выводим подсказки и предупреждения

    \if :pspg_installed
    \else
        \echo :hint'HINT: alternative pager "pspg" is supported and highly recommended to use, see https://github.com/okbob/pspg':reset
    \endif

    \if :is_superuser
    \else
        \echo :hint'HINT: use to connect a user (for example, postgres) with the superuser attribute to show more information and validate configuration files':reset
    \endif

    \if :is_local_connection
    \else
        \echo :hint'HINT: use local connection to show more details (directories size and etc.)':reset
    \endif

    \if :{?used_shared_buffers}
    \else
        \echo :hint'HINT: run "create extension pg_buffercache;" to show used/free cache size':reset
    \endif

    \if :{?logging_collector}
        \if :logging_collector
        \else
            \echo :warn'WARNING: logging collector is disabled, it is recommended to enable':reset
            \echo :hint'HINT: errors are redirected to syslog':reset
        \endif
    \endif

    \if :{?is_calc_dir_size_slow}
        \if :is_calc_dir_size_slow
            \echo :hint'HINT: calculating the directories size is slow, to disable the calculation, run `psql -v pro=0`':reset
        \endif
    \endif

    \if :{?data_directory_mounted_to}
        \if `test ':data_directory_mounted_to' = '/' && echo 1 || echo 0`
            \echo :warn'WARNING: data directory "':data_directory'" mounted to "/", it is recommended to create a separate partition with a dedicated quota of free space':reset
        \endif
    \endif

    \if :{?wal_directory_mounted_to}
        \if `test ':wal_directory_mounted_to' = '/' && echo 1 || echo 0`
            \echo :warn'WARNING: wal directory "':wal_dir'" mounted to "/", it is recommended to create a separate partition with a dedicated quota of free space':reset
        \endif
        select :'wal_directory_mounted_to' = :'data_directory_mounted_to' as flag \gset
        \if :flag
            \echo :hint'HINT: wal directory "':wal_directory'" mount point is the same, that "':data_directory'". It is recommended to separate the mount points into different partitions with a dedicated quota of free space':reset
        \endif
    \endif

    \if :{?log_directory_mounted_to}
        \if `test ':log_directory_mounted_to' = '/' && echo 1 || echo 0`
            \echo :warn'WARNING: log directory "':log_directory'" mounted to "/", it is recommended to create a separate partition with a dedicated quota of free space':reset
        \endif
        select :'log_directory_mounted_to' in (:'data_directory_mounted_to', :'wal_directory_mounted_to') as flag \gset
        \if :flag
            \echo :warn'WARNING: log directory "':log_directory'" mount point is the same, that "':data_directory'" or "':wal_directory'". It is recommended to separate the mount points into different partitions with a dedicated quota of free space':reset
        \endif
    \endif

    --------------------------------------------------------------------------------------------------------------------
    \if :is_superuser
        -- проверяем наличие ошибок в конфигурационных файлах
        \include ~/psqlrc/validate.psql
    \endif

    -- отображаем длительность выполнения запроса
    \timing 1

    -- отображаем количество строк под таблицей
    \pset footer on

\endif

-- восстанавливаем флаг отображения информационных сообщений
\set QUIET :QUIET_ORIGINAL
