-- устанавливает или сбрасывает заголовок для таблиц

\include ~/psqlrc/quiet_in.psql

select exists (select from pg_catalog.pg_namespace where nspname = 'pro') as schema_pro_exists \gset

\include ~/psqlrc/quiet_out.psql

\if :QUIET_ORIGINAL
\else
    \set QUIET 1
    \if :{?title}
        \set now `date --rfc-3339=seconds | sed 's/:00$//'`
        \pset title :title' (at ':now')'
    \else
        -- unset
        \pset title
    \endif
    \set QUIET 0
\endif
